from __future__ import annotations

from typing import Protocol

from ..models import AgentJob, AgentRole, Artifact, IntegrationItem, IntegrationItemStatus, IntegrationRun, IntegrationRunStatus, JobAttempt, JobEvent, JobStatus


class OrchestrationRepository(Protocol):
    backend_name: str
    database_url: str

    def initialize(self) -> None: ...
    def create_root_job(
        self, subject: str, instruction: str, role: AgentRole = AgentRole.GENERAL,
        status: JobStatus = JobStatus.QUEUED,
    ) -> AgentJob: ...
    def create_job(self, job: AgentJob) -> AgentJob: ...
    def get_job(self, job_id: str) -> AgentJob | None: ...
    def list_jobs(self, root_task_id: str | None = None, status: JobStatus | None = None) -> list[AgentJob]: ...
    def start_attempt(self, job_id: str, model: str = "") -> JobAttempt: ...
    def claim_next_job(self, model: str = "") -> tuple[AgentJob, JobAttempt] | None: ...
    def register_worker_pid(self, job_id: str, attempt_id: str, worker_token: str, pid: int) -> None: ...
    def running_worker_processes(self) -> list[tuple[str, int]]: ...
    def request_cancel(self, job_id: str) -> AgentJob: ...
    def timeout_attempt(self, attempt_id: str) -> AgentJob | None: ...
    def recover_interrupted_jobs(self) -> int: ...
    def requeue_retryable_jobs(self) -> int: ...
    def finish_attempt(self, attempt_id: str, status: JobStatus, *, artifact: Artifact | None = None, error: str = "", terminal_reason: str = "") -> AgentJob: ...
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...
    def list_events(self, job_id: str) -> list[JobEvent]: ...
    def create_integration_run(self, run: IntegrationRun, items: list[IntegrationItem]) -> IntegrationRun: ...
    def get_integration_run(self, run_id: str) -> IntegrationRun | None: ...
    def list_integration_items(self, run_id: str) -> list[IntegrationItem]: ...
    def transition_integration_item(self, item_id: str, status: IntegrationItemStatus, error: str = "") -> None: ...
    def transition_integration_run(self, run_id: str, status: IntegrationRunStatus, result_commit: str = "", error: str = "") -> None: ...
